name: Build and upload

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Generate build
        run: CI="" npm run build
      - name: Upload artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  release-pre:
    runs-on: ubuntu-latest
    needs: [build]
    if: endsWith(github.ref, '-dev')
    steps:
      - name: Download artifact of build job
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: build
          generate_release_notes: true

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: endsWith(github.ref , '-dev') != true
    steps:
      - name: Download artifact of build job
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build
          generate_release_notes: true
